[package]
name = "terrustaria"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9.1"
bevy_ecs_tilemap = "0.9.0"
rand = "0.8.4"
bevy_rapier2d = "0.19.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
default = ["bevy_rapier2d/debug-render"]
